-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ingredient_categories
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ingredient_categories_pkey PRIMARY KEY (id),
    CONSTRAINT ingredient_categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.ingredients
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category_id integer,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ingredients_pkey PRIMARY KEY (id),
    CONSTRAINT ingredients_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.recipe_categories
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT recipe_categories_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.recipe_ingredients
(
    id serial NOT NULL,
    recipe_id integer NOT NULL,
    ingredient_id integer NOT NULL,
    quantity numeric(10, 2),
    unit_id integer,
    notes character varying(100) COLLATE pg_catalog."default",
    order_index integer DEFAULT 0,
    CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.recipes
(
    id serial NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    instructions text COLLATE pg_catalog."default" NOT NULL,
    preparation_time integer,
    cooking_time integer,
    difficulty_level integer,
    servings integer,
    user_id integer NOT NULL,
    category_id integer,
    image_url character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_public boolean DEFAULT true,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT recipes_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.recipes
    IS 'Таблица рецептов';

COMMENT ON COLUMN public.recipes.difficulty_level
    IS 'Уровень сложности от 1 до 5';

COMMENT ON COLUMN public.recipes.status
    IS 'Статус рецепта: draft, active, archived';

CREATE TABLE IF NOT EXISTS public.reviews
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    recipe_id integer NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.reviews
    IS 'Таблица отзывов и оценок рецептов';

COMMENT ON COLUMN public.reviews.rating
    IS 'Оценка от 1 до 5 звезд';

CREATE TABLE IF NOT EXISTS public.units
(
    id serial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    abbreviation character varying(10) COLLATE pg_catalog."default",
    is_metric boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT units_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_ingredients
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    ingredient_id integer NOT NULL,
    quantity numeric(10, 2),
    unit_id integer,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone,
    CONSTRAINT user_ingredients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

COMMENT ON TABLE public.users
    IS 'Таблица пользователей системы';

COMMENT ON COLUMN public.users.username
    IS 'Уникальное имя пользователя (мин. 3 символа)';

COMMENT ON COLUMN public.users.is_active
    IS 'Флаг активности пользователя';

ALTER TABLE IF EXISTS public.ingredients
    ADD CONSTRAINT fk_ingredients_category_id FOREIGN KEY (category_id)
    REFERENCES public.ingredient_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_ingredients_category_id
    ON public.ingredients(category_id);


ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_ingredient_id FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_ingredient_id
    ON public.recipe_ingredients(ingredient_id);


ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_recipe_id FOREIGN KEY (recipe_id)
    REFERENCES public.recipes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id
    ON public.recipe_ingredients(recipe_id);


ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD CONSTRAINT fk_recipe_ingredients_unit_id FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.recipes
    ADD CONSTRAINT fk_recipes_category_id FOREIGN KEY (category_id)
    REFERENCES public.recipe_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_recipes_category_id
    ON public.recipes(category_id);


ALTER TABLE IF EXISTS public.recipes
    ADD CONSTRAINT fk_recipes_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipes_user_id
    ON public.recipes(user_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_recipe_id FOREIGN KEY (recipe_id)
    REFERENCES public.recipes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reviews_recipe_id
    ON public.reviews(recipe_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_ingredients
    ADD CONSTRAINT fk_user_ingredients_ingredient_id FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_ingredients
    ADD CONSTRAINT fk_user_ingredients_unit_id FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_ingredients
    ADD CONSTRAINT fk_user_ingredients_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_ingredients_user_id
    ON public.user_ingredients(user_id);

END;